language: go
go:
- '1.10'
deploy:
  provider: heroku
  api_key:
    secure: YaTvAgBKmTk1UdAwxLw/b2tDGQlOw0oFLZDRaY6lSjLNkHgWv0JKpQuDpKXKke7CuKsb+kMWv+RnCbPzgCptzandTN2BDMbCUw45h4yzTX5bH7/NbEamHLoY/eEja62EsTLi/Fcg+f8i/21znTGIJ9lp+0+X1YxzZZECKKYgsNAK/jcfq36SkerToUQMIaE7D6DAuERZzATzZOUZa/dq5PzpjM2GieMab4j13dYvX3p7OY5FJqVlymFF0ahOG+B3drtXesQ1AQLpo9LylU6mTul/9mjNC/EP/xI6nbEmTC6kbtNV8UeYGHJYl+fmmlBxmNInSYlsc6wXzQxo2kU4Skk6PmzSiWHTBMyRbtUvKo0o4J0upoTNlm10lOHm6v9RFXiNZ0aP7KyIMI8j+AuwrNxLWlY4bXXrxoM2dnQP0EszqVktCuxsojUyyrnV+yA1bL3AqRSgBAMhEex8TYbdUKvxIyFLQJnHygzcJQJXEay5YuNDyKTGcqigvgx7B0fpa3EYcNeDKz47g/NRf8PyWnMv/jlS9tQUkcAhUDMR6zUair7tzxSiN4kN3dfTzvrJiw98KIA3tvaawfNSB6njHXSjUpo9YHo2sr64KwVfg9+LCsdd/M6QzHN+lT5M9wPDvFsG6wSXJpKeuO8QcfUsieCq21pN1mMaQ6fTDIi3kl8=
  app: budget-report
