language: go
go:
  - '1.10'
deploy:
  provider: heroku
  api_key:
    secure: Y9aG9YaChRXdiH+GLuvXqpRhGxrErI36RvfG957uCYFpJUuPpzr5Si1TASYSNJukPkzH/xbm/VBksT1TAiW+ArCT1gOyBtoWWRX2yWZq3sGA1W5bknX5ZdyTyHouoewQftdoV0YifglENY13XeZ4lFsPcGgKRWWqgWxstWG7IqTcfd9Q0/BE9n/+goG3dTDq0Kuj0V3eLH0m6CtgzWlrvL6UobDqTiiKRuZ3mbXVq291sK7tmGyScLxAOy58G6ezEzBs00aRXwVlgpAKLK1GyljcryEc/b9smjvn/p2Hl+G5d7QAUDpPQXWPWyZHmQXih3ZF2xjRTX31zPQWHlJtAF2nv203ESPcNia5l4SH+wvTInCCnR60z4ybo8HeUZmtFtdjY/k4/5tfQwQ5buhVCSGruh9q68i8RNS3HG+e+bc0L+L6LnRABnBQoL/GVCSZQpWTCA3sju59ccZvBetHC04JHGm78Ttjd5e2bareO4KjjVg4g2OsYNMp9XRmX6zQBb/YIfSwRoQ3cdaIPxFDXJqP2c4h6wl39PXRPPd3/xa7sG9rdbN4isPCxPxM51XSPDJYJ0PFfDRnPHrTu+3vc96tYwqyyVoaiaeIxLNNWCAJHdJnizbTVO8Ax5L3CxLVeEc5AhX/wM2HQoCANALSk08aTic47cyVLWdeiDN5MNo=
